# Generated by Django 2.0.2 on 2018-03-20 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20)),
                ('ISSN', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=40)),
                ('cover_type', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('physical_description', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='SoftwareBiblio.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoftwareBiblio.Book')),
            ],
            options={
                'db_table': 'copy',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('fee_time', models.DateTimeField()),
                ('fee', models.FloatField()),
                ('fee_per_book', models.FloatField()),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'registered_user',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoftwareBiblio.Book')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'serie',
            },
        ),
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unregistered_user',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('registereduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SoftwareBiblio.RegisteredUser')),
            ],
            options={
                'db_table': 'administrator',
            },
            bases=('SoftwareBiblio.registereduser',),
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SoftwareBiblio.Image')),
            ],
            options={
                'db_table': 'book_cover',
            },
            bases=('SoftwareBiblio.image',),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SoftwareBiblio.Image')),
            ],
            options={
                'db_table': 'profile_picture',
            },
            bases=('SoftwareBiblio.image',),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoftwareBiblio.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader', to='SoftwareBiblio.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='copy',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SoftwareBiblio.Loan'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='SoftwareBiblio.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SoftwareBiblio.Serie'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='profile_picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SoftwareBiblio.ProfilePicture'),
        ),
        migrations.AddField(
            model_name='loan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='SoftwareBiblio.Administrator'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SoftwareBiblio.BookCover'),
        ),
    ]
